apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: devl
            cluster: https://kubernetes.default.svc
            targetRevision: sprint/2025q4
          - env: test
            cluster: https://kubernetes.default.svc
            targetRevision: test
      - git:
          repoURL: https://github.com/uidaho-ryanjt/banner-bootstrap
          revision: main
          files:
          - path: "apps-config.yaml"
  template:
    metadata:
      name: '{{.name}}'
      labels:
        app: '{{.name}}'
        environment: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        targetRevision: '{{.targetRevision}}'
        path: '{{.manifests_path}}/{{.env}}'  # This will become: src/kubernetes/overlay/devl
      destination:
        server: '{{.cluster}}'
        namespace: '{{.namespace}}-{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
