apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      # First generator: List of environments
      - list:
          elements:
          - env: devl
            cluster: https://kubernetes.default.svc
          - env: test
            cluster: https://kubernetes.default.svc
          - env: prod
            cluster: https://kubernetes.default.svc
      # Second generator: Read apps from config file
      - git:
          repoURL: https://dev.azure.com/YOUR-ORG/YOUR-PROJECT/_git/argocd-bootstrap
          revision: main
          files:
          - path: "apps-config.yaml"
  template:
    metadata:
      name: '{{.name}}-{{.env}}'
      labels:
        app: '{{.name}}'
        environment: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        targetRevision: main
        path: '{{.manifests_path}}/{{.env}}'  # Changed from {{.path}}/{{.env}}
      destination:
        server: '{{.cluster}}'
        namespace: '{{.namespace}}-{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
