- name: application-navigator
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/application-navigator
  manifests_path: src/kubernetes/overlays
  namespace: application-navigator
- name: azure-devops-agents
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/azure-devops-agents
  manifests_path: src/kubernetes/overlays
  namespace: azure-devops-agents
- name: banner-8
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-8
  manifests_path: src/kubernetes/overlays
  namespace: banner-8
- name: banner-access-management
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-access-management
  manifests_path: src/kubernetes/overlays
  namespace: banner-access-management
- name: banner-admin
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-admin
  manifests_path: src/kubernetes/overlays
  namespace: banner-admin
- name: banner-admin-bpapi
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-admin-bpapi
  manifests_path: src/kubernetes/overlays
  namespace: banner-admin-bpapi
- name: Banner-Cluster
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/Banner-Cluster
  manifests_path: src/kubernetes/overlays
  namespace: banner-cluster
- name: banner-event-publisher
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-event-publisher
  manifests_path: src/kubernetes/overlays
  namespace: banner-event-publisher
- name: banner-extensibility
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-extensibility
  manifests_path: src/kubernetes/overlays
  namespace: banner-extensibility
- name: banner-workflow
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/banner-workflow
  manifests_path: src/kubernetes/overlays
  namespace: banner-workflow
- name: cluster-networking
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/cluster-networking
  manifests_path: src/kubernetes/overlays
  namespace: cluster-networking
- name: cluster-security
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/cluster-security
  manifests_path: src/kubernetes/overlays
  namespace: cluster-security
- name: cluster-support
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/cluster-support
  manifests_path: src/kubernetes/overlays
  namespace: cluster-support
- name: college-scheduler
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/college-scheduler
  manifests_path: src/kubernetes/overlays
  namespace: college-scheduler
- name: communication-management
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/communication-management
  manifests_path: src/kubernetes/overlays
  namespace: communication-management
- name: config-maps-banner
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/config-maps-banner
  manifests_path: src/kubernetes/overlays
  namespace: config-maps-banner
- name: db-access-transfers
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/db-access-transfers
  manifests_path: src/kubernetes/overlays
  namespace: db-access-transfers
- name: degree-works-apiservices
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/degree-works-apiservices
  manifests_path: src/kubernetes/overlays
  namespace: degree-works-apiservices
- name: degree-works-controller
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/degree-works-controller
  manifests_path: src/kubernetes/overlays
  namespace: degree-works-controller
- name: degree-works-dashboard
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/degree-works-dashboard
  manifests_path: src/kubernetes/overlays
  namespace: degree-works-dashboard
- name: degree-works-itransfer
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/degree-works-itransfer
  manifests_path: src/kubernetes/overlays
  namespace: degree-works-itransfer
- name: degree-works-transit
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/degree-works-transit
  manifests_path: src/kubernetes/overlays
  namespace: degree-works-transit
- name: ellucian-messaging-adapter
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/ellucian-messaging-adapter
  manifests_path: src/kubernetes/overlays
  namespace: ellucian-messaging-adapter
- name: employee-self-service
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/employee-self-service
  manifests_path: src/kubernetes/overlays
  namespace: employee-self-service
- name: etranscript-api
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/etranscript-api
  manifests_path: src/kubernetes/overlays
  namespace: etranscript-api
- name: faculty-self-service
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/faculty-self-service
  manifests_path: src/kubernetes/overlays
  namespace: faculty-self-service
- name: finance-self-service
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/finance-self-service
  manifests_path: src/kubernetes/overlays
  namespace: finance-self-service
- name: general-self-service
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/general-self-service
  manifests_path: src/kubernetes/overlays
  namespace: general-self-service
- name: integration-api
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/integration-api
  manifests_path: src/kubernetes/overlays
  namespace: integration-api
- name: jasper
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/jasper
  manifests_path: src/kubernetes/overlays
  namespace: jasper
- name: market-rate
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/market-rate
  manifests_path: src/kubernetes/overlays
  namespace: market-rate
- name: net-price-calculator
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/net-price-calculator
  manifests_path: src/kubernetes/overlays
  namespace: net-price-calculator
- name: nginx-custom-pages
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/nginx-custom-pages
  manifests_path: src/kubernetes/overlays
  namespace: nginx-custom-pages
- name: people-images
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/people-images
  manifests_path: src/kubernetes/overlays
  namespace: people-images
- name: priority-classes
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/priority-classes
  manifests_path: src/kubernetes/overlays
  namespace: priority-classes
- name: public-class-schedule
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/public-class-schedule
  manifests_path: src/kubernetes/overlays
  namespace: public-class-schedule
- name: rabbitmq
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/rabbitmq
  manifests_path: src/kubernetes/overlays
  namespace: rabbitmq
- name: registration-self-service
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/registration-self-service
  manifests_path: src/kubernetes/overlays
  namespace: registration-self-service
- name: student-api
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/student-api
  manifests_path: src/kubernetes/overlays
  namespace: student-api
- name: student-self-service
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/student-self-service
  manifests_path: src/kubernetes/overlays
  namespace: student-self-service
- name: tncommerce
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/tncommerce
  manifests_path: src/kubernetes/overlays
  namespace: tncommerce
- name: utilities
  repo: https://dev.azure.com/uidaho/Banner-Cluster/_git/utilities
  manifests_path: src/kubernetes/overlays
  namespace: utilities
